### ISSUE TITLE
Error in calculateCardSetStars 

### ISSUE THREAD

**Issue by Mohron** [Morta1/idleon-data-extractor#2]
```
Error in event handler: TypeError: Cannot read properties of undefined (reading 'base') at calculateCardSetStars (chrome-extension://chkngdmlnaflpphdjjaappeijfapnoho/background.js:394:14) at chrome-extension://chkngdmlnaflpphdjjaappeijfapnoho/background.js:288:18 at Array.map (<anonymous>) at buildCharacterData (chrome-extension://chkngdmlnaflpphdjjaappeijfapnoho/background.js:185:23) at parseData (chrome-extension://chkngdmlnaflpphdjjaappeijfapnoho/background.js:95:24) at chrome-extension://chkngdmlnaflpphdjjaappeijfapnoho/background.js:48:31
```

I just got my 9th character and I had forgotten to give them a card set... after I set one and went to the main menu, the plugin worked again. Seems the code assumes you have a card set applied.

**Comment by Morta1** [comment]
Thanks, found the issue 👍
